### ISSUE TITLE
[BUG] Version missmatch 

### ISSUE THREAD

**Issue by uhlhosting** [JeffVandrewJr/patron#18]
**Describe the bug**

**To Reproduce**
Deploy latest released btcpayserver-docker
Install patron via btcpay server

If one checks the 

```
docker-compose-generator/docker-fragments/opt-add-librepatron.yml                                         
version: '3'
services:
    librepatron:
        container_name: librepatron
        restart: unless-stopped
        image: jvandrew/librepatron:0.7.39
```

**Expected behavior**
To get version 0.7.39

**Screenshots**
In reality we get 0.7.37

<img width="487" alt="image" src="https://user-images.githubusercontent.com/6324047/109359274-7b53b900-7885-11eb-86ea-87d78fdac624.png">

Now I am not sure if this is a typo somewhere so it seems to me. Maybe forgot to bump the version in latest release?
**Additional context**
